[project]
name = "modeus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
    "selenium>=4.26.1",
]

[dependency-groups]
dev = [
    "pip>=24.3.1",
]
